parameters:
    json_rpc_api.remote_object.universal_wrapper.class: Insidestyles\JsonRpcBundle\Sdk\RemoteObject\UniversalWrapper

services:

    json_rpc_api.handler.locator:
        class: 'Insidestyles\JsonRpcBundle\Server\HandlersLocator'

    Insidestyles\JsonRpcBundle\Server\HandlersLocator: '@json_rpc_api.handler.locator'

    json_rpc_api.controller:
        class: 'Insidestyles\JsonRpcBundle\Controller\ApiController'
        public: true
        arguments:
            - '@json_rpc_api.handler.locator'
        calls: [['setContainer', ['@service_container']]]

    Insidestyles\JsonRpcBundle\Controller\ApiController: '@json_rpc_api.controller'

    json_rpc_api.routing.loader:
        class: 'Insidestyles\JsonRpcBundle\Routing\ApiRoutingLoader'
        tags:
            - { name: 'routing.loader' }

    Insidestyles\JsonRpcBundle\Routing\ApiRoutingLoader: '@json_rpc_api.routing.loader'

    json_rpc_api.serializer.default_context:
        class: 'Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\DefaultSerializerContext'

    Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\DefaultSerializerContext: '@json_rpc_api.serializer.default_context'

    json_rpc_api.serializer.jms_abstract:
        class: 'Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\JmsSerializer'
        abstract: true
        arguments:
            - '@jms_serializer.serializer'

    Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\JmsSerializer: '@json_rpc_api.serializer.jms_abstract'

    json_rpc_api.serializer.symfony_abstract:
        class: 'Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\SymfonySerializer'
        abstract: true
        arguments:
            - '@serializer'

    Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\SymfonySerializer: '@json_rpc_api.serializer.symfony_abstract'

    json_rpc_api.serializer.default:
        class: 'Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\DefaultSerializer'

    Insidestyles\JsonRpcBundle\Server\Adapter\Serializer\DefaultSerializer: '@json_rpc_api.serializer.default'

    json_rpc_api.server.json_rpc_abstract:
        abstract: true
        class: 'Laminas\Json\Server\Server'

    Laminas\Json\Server\Server: '@json_rpc_api.server.json_rpc_abstract'

    json_rpc_api.handler.json_rpc_abstract:
        abstract: true
        class: 'Insidestyles\JsonRpcBundle\Server\Handler\JsonRpcHandler'
        arguments:
            - '@json_rpc_api.server.json_rpc_abstract'
            - ~
            - '@json_rpc_api.serializer.default'
            - '@json_rpc_api.serializer.default_context'
            - ~

    Insidestyles\JsonRpcBundle\Server\Handler\JsonRpcHandler: '@json_rpc_api.handler.json_rpc_abstract'

    json_rpc_api.remote_service.universal_wrapper_abstract:
        abstract: true
        class: 'Insidestyles\JsonRpcBundle\Sdk\RemoteObject\UniversalWrapper'
        arguments:
            - ~
            - ~
            - ~
            - ~

    Insidestyles\JsonRpcBundle\Sdk\RemoteObject\UniversalWrapper: '@json_rpc_api.remote_service.universal_wrapper_abstract'

    json_rpc_api.client.http_client_abstract:
        abstract: true
        class: 'Laminas\Http\Client'
        arguments:
            - ~
            - {timeout: 60}
            - ~

    Laminas\Http\Client: '@json_rpc_api.client.http_client_abstract'

    json_rpc_api.error_handler.manager:
        class: 'Insidestyles\JsonRpcBundle\Server\ErrorHandler\ErrorHandlerManager'

    Insidestyles\JsonRpcBundle\Server\ErrorHandler\ErrorHandlerManagerInterface: '@json_rpc_api.error_handler.manager'

    json_rpc_api.error_handler.handler.handler_failed_exception:
        autowire: true
        class: 'Insidestyles\JsonRpcBundle\Server\ErrorHandler\Handler\HandlerFailedExceptionHandler'
        tags:
            - { name: 'json_rpc_api.error_handler' }

    json_rpc_api.error_handler.handler.json_rpc_error:
        class: 'Insidestyles\JsonRpcBundle\Server\ErrorHandler\Handler\JsonRpcErrorHandler'
        tags:
            - { name: 'json_rpc_api.error_handler' }

    json_rpc_api.error_handler.handler.symfony_validation_exception:
        class: 'Insidestyles\JsonRpcBundle\Server\ErrorHandler\Handler\SymfonyValidationErrorHandler'
        tags:
            - { name: 'json_rpc_api.error_handler' }